### ISSUE TITLE
can not create pull requests - github-oauth.github.com is not defined

### ISSUE THREAD

**Issue by photodude** [crysalead/chaos#1]
the .travis.yml config prevents creating pull requests (the secure value does not export for forks/pull-requests)

see 
https://travis-ci.org/photodude/chaos-orm/jobs/208200569#L129-L134

**Comment by jails** [comment]
Thanks for the head up, the issue should have been fixed in https://github.com/crysalead/chaos-orm/commit/e9bb801966d212eb76dbfaaee7362633a7ff7511

**Comment by photodude** [comment]
That seems to work. Closing as fixed.
I can run the tests to see the HHVM issues you were having now
https://travis-ci.org/photodude/chaos-orm/jobs/208214986

**Comment by jails** [comment]
Indeed, I experienced a lot of issues by supporting HHVM on some other libraries. Now HHVM is stuck on the following longstanding https://github.com/facebook/hhvm/issues/7198 which is kind painful. So I'll probably wait to see how HHVM will evolve in the futur to see if it worth the effort but thanks for sharing the report :+1:

**Comment by photodude** [comment]
Ya, that issue has been a pain. Composer is addressing some of the issues related to composer installs from their end, but that doesn't fix issues related to HHVM's bad idea to enforce the behavior of PHP 7 in strict mode declare (strict_types=1) on all files (in php 7 it's a per file enforcement) which breaks frameworks and basically everything else.
